const translations = {
    '0': {
        //////////Top and Sidebar
        '_PHOTOGRAPHER': 'Photographer',
        '_LOGOUT': 'Logout',

        /////////login screen
        '_LOGIN_TO_YOUR_ACCOUNT': 'LOGIN TO YOUR ACCOUNT',
        '_EMAIL': 'Email',
        '_PHONE':'Phone',
        '_PASSWORD': 'Password',
        '_LOGIN': 'LOGIN',
        '_CREATE_AN_ACCOUNT': 'Create an account',
        /////////register screen
        '_CREATE_AN_ACCOUNT_R': 'CREATE AN ACCOUNT',
        '_NAME': 'Name',
        '_PASSWORD_CONFIRM': 'Password (Confirm)',
        '_CONDITIONS': 'I read and accept terms and conditions',
        '_LOGIN_R': 'Login',
        ///////Users screen
        '_START_DATE': 'Start date',
        '_GENERATE': 'Generate',
        '_CODE': 'Code',
        '_DURATION': 'Duration',
        '_DELETE': 'Delete',
        '_VIEW': 'View',
        '_USERS_ADD_EXPIRATION_DATE': 'Please set expiratin days',
        '_USERS_EXPIRATION_DATE': 'Expiration Days',
        '_DELETE_USER': 'Are you sure to delete this user?',

        //////////Galleries screen
        '_GALLERY_NAME': 'Gallery name',
        '_EDIT_GALLERY': 'Edit gallery',
        '_DELETE_GALLERY': 'Delete gallery',
        '_ADD_GALLERY': 'Add gallery',
        '_EDIT': 'Edit',
        'GALLERY_MODAL_DELETE': 'Are you sure want to delete this gallery?',
        'GALLERY_MODAL_EDIT': 'Are you going to edit gallery name?',
        //////////Images Screen
        '_FILTER': 'Filter',
        '_SHOW_ALL': 'Show All',
        '_ADD_IMAGES': 'Add images',
        '_FILE_NAME': 'File name',
        '_IMAGE': 'Image',
        '_IMAGE_MODAL_DELETE_IMAGE': 'Are you sure want to delete this image?',
        //////////content Screen
        '_ARTICLES': 'Articles',
        '_USERS': 'Users',
        '_GALLERIES': 'Galleries',
        '_ADD_ARTICLE': 'Add article',
        '_EDIT_ARTICLE_INFO': 'Edit Article Info',
        '_NO': 'No',
        '_TITLE': 'Title',
        '_STATUS': 'Status',
        '_STICKY': 'Sticky',
        '_DATE_TIME': 'DateTime',
        '_MAIN_IMAGE': 'Main image',
        '_DELETE_IMAGE': 'Delete image',
        '_DELETE_ARTICLE': 'Delete Article',
        '_CONTENT_MODAL_TITLE': 'Add Article Info',
        '_TRUE': 'True',
        '_FALSE': 'False',
        '_DATE': 'Date',
        '_DISAGREE': 'Disagree',
        '_AGREE': 'Agree',
        '_ARTICLE_DELETE': 'Are you sure want to delete this article?',
        '_VIEW_IMAGES': 'View Images',
        '_ABOUT':'Set as about',
    },
    '1': {
        //////////Top and Sidebar
        '_PHOTOGRAPHER': 'צלם',
        '_LOGOUT': 'להתנתק',

        /////////login screen
        '_LOGIN_TO_YOUR_ACCOUNT': 'התחבר לחשבונך',
        '_EMAIL': 'אימייל',
        '_PHONE':'מכשיר טלפון',
        '_PASSWORD': 'סיסמה',
        '_LOGIN': 'התחברות',
        '_CREATE_AN_ACCOUNT': 'צור חשבון',
        /////////register screen
        '_CREATE_AN_ACCOUNT_R': 'צור חשבון',
        '_NAME': 'שם',
        '_PASSWORD_CONFIRM': 'אישור סיסמה',
        '_CONDITIONS': ' קראתי וקיבלתיאת כל התנאים והגבלות',
        '_LOGIN_R': 'התחברות',
        ///////Users screen
        '_START_DATE': 'תאריך התחלה',
        '_GENERATE': 'צור',
        '_CODE': 'קוד',
        '_DURATION': 'משך הזמן',
        '_DELETE': 'מחק',
        '_VIEW': 'תצוגה',
        '_USERS_ADD_EXPIRATION_DATE': 'אנא קבע ימי תפוגה',
        '_USERS_EXPIRATION_DATE': 'ימי תפוגה',
        '_DELETE_USER': 'האם אתה בטוח למחוק משתמש זה?',
        //////////Galleries screen
        '_GALLERY_NAME': 'שם הגלריה',
        '_EDIT_GALLERY': 'ערוך גלריה',
        '_DELETE_GALLERY': 'מחק גלריה',
        '_ADD_GALLERY': 'הוסף גלריה',
        '_EDIT': 'ערוך',
        'GALLERY_MODAL_DELETE': 'האם אתה בטוח שברצונך למחוק את הגלריה הזו?',
        'GALLERY_MODAL_EDIT': 'האם אתה מתכוון לערוך את שם הגלריה?',
        //////////Images Screen
        '_FILTER': 'סנן',
        '_SHOW_ALL': 'הצג הכול',
        '_ADD_IMAGES': 'הוסף תמונות',
        '_FILE_NAME': 'שם קובץ',
        '_IMAGE': 'תמונה',
        '_IMAGE_MODAL_DELETE_IMAGE': 'האם אתה בטוח שברצונך למחוק תמונה זו?',
        //////////content Screen
        '_ARTICLES': 'מאמרים',
        '_USERS': 'משתמשים',
        '_GALLERIES': 'גלריות',
        '_ADD_ARTICLE': 'הוסף מאמר',
        '_EDIT_ARTICLE_INFO': 'הוסף מידע על המאמר',
        '_NO': 'לא',
        '_TITLE': 'כותרת',
        '_STATUS': 'סטטוס',
        '_STICKY': 'דביק',
        '_DATE_TIME': 'תאריך שעה',
        '_MAIN_IMAGE': 'תמונה ראשית',
        '_DELETE_IMAGE': 'מחק תמונה',
        '_DELETE_ARTICLE': 'מחק את המאמר',
        '_CONTENT_MODAL_TITLE': 'אנא הוסף את פרטי המאמר',
        '_TRUE': 'נכון',
        '_FALSE': 'לא נכון',
        '_DATE': 'תאריך',
        '_DISAGREE': 'לא מסכים',
        '_AGREE': 'מסכים',
        '_ARTICLE_DELETE': 'האם אתה בטוח שברצונך למחוק מאמר זה?',
        '_VIEW_IMAGES': 'צפו בתמונות',
        '_ABOUT':'הגדר כאמור',
    },
    '2': {
        //////////Top and Sidebar
        '_PHOTOGRAPHER': 'مصور فوتوغرافي',
        '_LOGOUT': 'تسجيل خروج',

        /////////login screen
        '_LOGIN_TO_YOUR_ACCOUNT': 'تسجيل الدخول إلى حسابك',
        '_EMAIL': 'البريد الإلكتروني',
        '_PHONE':'هاتف',
        '_PASSWORD': 'كلمه السر',
        '_LOGIN': 'تسجيل الدخول',
        '_CREATE_AN_ACCOUNT': 'انشاء حساب',
        /////////register screen
        '_CREATE_AN_ACCOUNT_R': 'انشاء حساب',
        '_NAME': 'اسم',
        '_PASSWORD_CONFIRM': 'تأكيد كلمة المرور',
        '_CONDITIONS': 'قرأت وأوافق على الشروط والأحكام',
        '_LOGIN_R': 'تسجيل الدخول',
        ///////Users screen
        '_START_DATE': 'تاريخ البدء',
        '_GENERATE': 'انشاء',
        '_CODE': 'رمز',
        '_DURATION': 'المدة الزمنية',
        '_DELETE': 'حذف',
        '_VIEW': 'المشاهدة',
        '_USERS_ADD_EXPIRATION_DATE': 'يرجى تحديد أيام انتهاء الصلاحية',
        '_USERS_EXPIRATION_DATE': 'أيام انتهاء الصلاحية',
        '_DELETE_USER': 'هل أنت متأكد من حذف هذا المستخدم؟',
        //////////Galleries screen
        '_GALLERY_NAME': 'اسم المعرض',
        '_EDIT_GALLERY': 'تحرير المعرض',
        '_DELETE_GALLERY': 'حذف المعرض',
        '_ADD_GALLERY': 'إضافة معرض',
        '_EDIT': 'تعديل',
        'GALLERY_MODAL_DELETE': 'هل تريد بالتأكيد حذف هذا المعرض؟',
        'GALLERY_MODAL_EDIT': 'هل ستقوم بتحرير اسم المعرض؟',
        //////////Images Screen
        '_FILTER': 'فلتر',
        '_SHOW_ALL': 'عرض الكل',
        '_ADD_IMAGES': 'إضافة الصور',
        '_FILE_NAME': 'اسم الملف',
        '_IMAGE': 'صورة',
        '_IMAGE_MODAL_DELETE_IMAGE': 'هل تريد بالتأكيد حذف هذه الصورة؟',
        //////////content Screen
        '_ARTICLES': 'مقالات',
        '_USERS': 'المستخدمين',
        '_GALLERIES': 'المعارض',
        '_ADD_ARTICLE': 'أضف مقال',
        '_EDIT_ARTICLE_INFO': 'إضافة معلومات المادة',
        '_NO': 'لا',
        '_TITLE': 'عنوان',
        '_STATUS': 'الحالة',
        '_STICKY': 'لزج',
        '_DATE_TIME': 'التاريخ والوقت',
        '_MAIN_IMAGE': 'الصورة الرئيسية',
        '_DELETE_IMAGE': 'حذف صورة',
        '_DELETE_ARTICLE': 'حذف المادة',
        '_CONTENT_MODAL_TITLE': 'يرجى إضافة معلومات المقالة',
        '_TRUE': 'صحيح',
        '_FALSE': 'خاطئة',
        '_DATE': 'تاريخ',
        '_DISAGREE': 'غير موافق',
        '_AGREE': 'موافق',
        '_ARTICLE_DELETE': 'هل تريد بالتأكيد حذف هذه المقالة؟',
        '_VIEW_IMAGES': 'عرض الصور',
        '_ABOUT':'تعيين كما هو',
    }
}

module.exports = translations;